<script setup>
import { ArrowRight, Briefcase, Storefront, UsersThree } from '../icons';
import AppBlock from '../components/AppBlock.vue';
import { pito } from '../stores/content';
</script>

<template>
  <section class="about-hero"><div class="shell about-hero-inner"><div class="about-hero-copy"><p class="eyebrow">Dit is PITO</p><h1>Niet nóg een sociaal netwerk. Wel een buurt die je weer leert kennen.</h1><p>PITO is je vriendelijke gids door de buurt. Hij houdt je op de hoogte, brengt mensen bij elkaar en helpt je vinden waar je aan mee wilt doen.</p><blockquote>“Ik zorg dat dichtbij weer voelt als dichtbij.”</blockquote><div class="hero-actions"><a class="button button--orange" :href="pito.links.app_download" target="_blank" rel="noopener">Download PITO</a><a class="button button--outline" href="#waarom">Waarom PITO bestaat</a></div></div><div class="about-hero-visual"><img src="/assets/pito-website-v18/deals-markt-korting.png" alt="Bewoners, ondernemers en PITO op de lokale markt" /><span>EEN KLEIN VOGELTJE.<br />MET EEN GROOT BEREIK.</span></div></div></section>
  <section id="waarom" class="about-story"><div class="shell about-story-grid"><div class="about-story-copy"><p class="eyebrow">Waarom we bestaan</p><h2>Dichtbij gebeurt genoeg. Alleen staat het overal.</h2><p>Een activiteit in een appgroep. Een hulpvraag op sociale media. Een vacature op een losse website. Lokaal aanbod in een nieuwsbrief. Waarde is er genoeg; overzicht ontbreekt.</p><p>PITO brengt bewoners, ondernemers, organisaties en lokale kansen samen in één vertrouwde omgeving, afgestemd op de gemeente en buurt waarin je woont.</p><p class="about-quote">PITO maakt dichtbij weer vindbaar.</p></div><div class="about-problem-list"><article><span>01</span><div><h3>Zie wat er speelt</h3><p>Van activiteiten en buurtnieuws tot lokale initiatieven.</p></div></article><article><span>02</span><div><h3>Vind elkaar</h3><p>Bewoners, ondernemers en organisaties op één vertrouwde plek.</p></div></article><article><span>03</span><div><h3>Kom in beweging</h3><p>Praat mee, doe mee of pak voordeel wanneer het bij je past.</p></div></article></div></div></section>
  <section class="about-manifesto"><div class="shell about-manifesto-inner"><div class="about-manifesto-copy"><p class="eyebrow eyebrow--light">Onze missie</p><h2>Nederland weer dichter bij elkaar brengen.<br /><span>Eén buurt tegelijk.</span></h2><p>Wij bouwen aan buurten waarin contact makkelijker begint, lokale organisaties zichtbaar blijven en geld vaker in de omgeving wordt besteed. Technologie is voor ons geen eindpunt, maar een uitnodiging om mee te doen.</p></div><div class="about-manifesto-visual"><img src="/assets/pito-mascotte/05_pito_buurthulp_meelevend.png" alt="PITO helpt buurtgenoten elkaar te vinden" /><strong>Dichtbij gevonden.<br />Samen meer voor elkaar.</strong></div></div></section>
  <section class="about-impact"><div class="shell"><div class="about-impact-heading"><p class="eyebrow eyebrow--light">De wereld van PITO</p><h2>Eén missie.<br /><span>Drie duidelijke ingangen.</span></h2><p>De app verbindt de buurt. Aanbod en vacatures krijgen een heldere eigen route, zodat je sneller vindt wat je zoekt.</p></div><div class="about-impact-groups"><article><div class="about-impact-marker"><UsersThree :size="25" /><span>01</span></div><div><small>De buurtapp</small><h3>Praat mee en ontdek wat dichtbij speelt.</h3><p>Activiteiten, verhalen en contact met mensen uit jouw omgeving.</p><a :href="pito.links.app_download" target="_blank" rel="noopener">Download PITO <ArrowRight :size="16" /></a></div></article><article><div class="about-impact-marker"><Storefront :size="25" /><span>02</span></div><div><small>Aanbod</small><h3>Voordeel zonder de buurtapp commercieel te maken.</h3><p>Lokale deals, vaste lasten en collectieven op één duidelijke plek.</p><RouterLink to="/deals">Bekijk aanbod <ArrowRight :size="16" /></RouterLink></div></article><article><div class="about-impact-marker"><Briefcase :size="25" /><span>03</span></div><div><small>Vacatures</small><h3>Werk en vrijwilligerswerk dichterbij.</h3><p>Kansen van bedrijven en organisaties in of rond jouw gemeente.</p><RouterLink to="/vacatures">Bekijk vacatures <ArrowRight :size="16" /></RouterLink></div></article></div></div></section>
  <AppBlock />
</template>
