<script setup>
import { ArrowRight, Briefcase, Check, Clock, MapPin, Storefront, UsersThree } from '../icons';
import { pito } from '../stores/content';
const packages = [
  { name: 'Starter', price: '€ 10', limit: '1 actieve plaatsing', note: 'in één gemeente', tone: 'blue', features: ['Vacature of aanbod', 'Zelf looptijd bepalen', 'E-mail vóór afloop'] },
  { name: 'Groei', price: '€ 30', limit: '6 actieve plaatsingen', note: 'verdeeld over gekozen gemeenten', tone: 'orange', featured: true, features: ['Vacatures én aanbod', 'Meerdere gemeenten', 'Direct aanpassen en verlengen'] },
  { name: 'Pro', price: '€ 50', limit: '18 actieve plaatsingen', note: 'voor structurele zichtbaarheid', tone: 'teal', features: ['Ruimte voor doorlopende campagnes', 'Meerdere vestigingen', 'Prioriteit bij zakelijke support'] },
];
</script>

<template>
  <section class="business-v2-hero"><div class="shell business-v2-hero-inner"><div class="business-v2-hero-copy"><p class="eyebrow">PITO voor bedrijven</p><h1>Lokale klanten vinden. Personeel dichtbij.</h1><p class="business-v2-hero-lead">Word zichtbaar in de gemeenten die voor jouw bedrijf tellen. Plaats een vacature, actie of vast aanbod zonder er een ingewikkeld advertentiekanaal bij te krijgen.</p><div class="business-v2-hero-actions"><a class="button button--orange" href="#zakelijk-publiceren">Bekijk de mogelijkheden</a><a class="button button--outline" :href="pito.links.business_login" target="_blank" rel="noopener">Zakelijk inloggen</a></div><div class="business-v2-hero-proof"><span>Ongeveer één minuut</span><span>Zelf je looptijd bepalen</span><span>Maandelijks opzegbaar</span></div></div><div class="business-v2-hero-visual"><img src="/assets/pito-website-v18/deals-bakker-app-korting.png" alt="Lokale ondernemer maakt aanbod zichtbaar via PITO" /><div><Storefront :size="24" /><span><small>DICHTBIJ GEVONDEN</small><strong>Aanbod én vacatures in jouw gemeente</strong></span></div></div></div></section>
  <section class="business-v2-manifesto"><div class="shell"><p class="eyebrow">Bereik dat ertoe doet</p><div><h2>Lokale bedrijven geven een buurt karakter.</h2><p>PITO helpt je zichtbaar te blijven voor inwoners in jouw directe omgeving. Via de website, de app, lokale campagnes en onze sociale kanalen.</p></div></div></section>
  <section id="zakelijk-publiceren" class="business-v2-paths"><div class="shell"><header class="business-v2-heading"><div><p class="eyebrow">Wat wil je bereiken?</p><h2>Twee routes. Allebei snel geregeld.</h2></div><p>Je maakt één account aan, kiest waar je zichtbaar wilt zijn en bepaalt zelf hoe lang je plaatsing loopt.</p></header><div class="business-v2-path-grid"><article class="business-v2-path business-v2-path--vacancy"><span class="business-v2-path-icon"><Briefcase :size="26" /></span><h3>Vind personeel dichtbij</h3><p>Breng vacatures onder de aandacht van mensen die al in de omgeving wonen of daar willen werken.</p><a :href="pito.links.business_signup" target="_blank" rel="noopener">Plaats een vacature <ArrowRight :size="18" /></a></article><article class="business-v2-path business-v2-path--offer"><span class="business-v2-path-icon"><Storefront :size="26" /></span><h3>Breng jouw aanbod onder de aandacht</h3><p>Kies een doorlopend aanbod of wissel acties wanneer jij wilt. Jij bepaalt de looptijd.</p><a :href="pito.links.business_signup" target="_blank" rel="noopener">Plaats mijn aanbod <ArrowRight :size="18" /></a></article></div><div class="business-v2-login"><Check :size="18" /> Registratie, betaling en beheer lopen veilig via pito.app <a :href="pito.links.business_login" target="_blank" rel="noopener">Ik heb al een account <ArrowRight :size="16" /></a></div></div></section>
  <section class="business-v2-reach"><div class="shell"><div class="business-v2-reach-intro"><p class="eyebrow">Wat levert het concreet op?</p><h2>Relevanter bereik. Minder verspilde aandacht.</h2><p>Je plaatsing verschijnt waar lokale inwoners al zoeken. Bovendien kan PITO nieuwkomers in een gemeente gericht laten kennismaken met wat er dichtbij beschikbaar is.</p></div><div class="business-v2-benefits"><article><span><MapPin :size="24" /></span><h3>Bereik per gemeente</h3><p>Kies zelf welke gemeenten tellen en voorkom bereik waar je niets aan hebt.</p></article><article><span><UsersThree :size="24" /></span><h3>Ook nieuwe inwoners</h3><p>Maak je bedrijf zichtbaar voor mensen die de omgeving nog aan het ontdekken zijn.</p></article><article><span><Clock :size="24" /></span><h3>Een minuut werk</h3><p>Plaats snel, kies je looptijd en ontvang een seintje voordat iets verloopt.</p></article></div></div></section>
  <section class="business-v2-platform"><div class="shell business-v2-platform-inner"><div><p class="eyebrow eyebrow--light">Zelf aan het stuur</p><h2>Generiek aanbod of iedere week iets nieuws.</h2><p>Laat een vaste dienst het hele jaar staan, of wissel acties en vacatures zo vaak als jouw bedrijf nodig heeft.</p></div><div class="business-v2-platform-list"><article><span>01</span><div><h3>Maak je plaatsing</h3><p>Voeg titel, foto, tekst, locatie en link toe.</p></div></article><article><span>02</span><div><h3>Kies gebied en looptijd</h3><p>Bepaal zelf waar en tot wanneer de plaatsing zichtbaar is.</p></div></article><article><span>03</span><div><h3>Direct live</h3><p>Na publicatie verschijnt je aanbod of vacature in de gekozen omgeving.</p></div></article><article><span>04</span><div><h3>Op tijd een seintje</h3><p>Voor het verloopt ontvang je een e-mail. Verlengen of vervangen is aan jou.</p></div></article></div></div></section>
  <section class="business-v2-pricing"><div class="shell"><header class="business-v2-pricing-heading"><div><p class="eyebrow">Eerlijke maandprijzen</p><h2>Begin met de ruimte die je nodig hebt.</h2></div><p>Dit zijn gewone maandprijzen, exclusief btw. Maandelijks opzegbaar en zonder lang contract.</p></header><div class="business-v2-package-grid"><article v-for="item in packages" :key="item.name" class="business-v2-package" :class="[`business-v2-package--${item.tone}`, { 'is-featured': item.featured }]"><span v-if="item.featured" class="business-v2-package-label">MEEST GEKOZEN</span><div class="business-v2-package-top"><h3>{{ item.name }}</h3><div class="business-v2-package-price"><strong>{{ item.price }}</strong><span>per maand<br />excl. btw</span></div></div><div class="business-v2-package-limit"><strong>{{ item.limit }}</strong><span>{{ item.note }}</span></div><ul><li v-for="feature in item.features" :key="feature"><Check :size="18" /> {{ feature }}</li></ul><a class="button button--orange" :href="pito.links.business_signup" target="_blank" rel="noopener">Kies {{ item.name.toLowerCase() }}</a></article></div><div class="business-v2-pricing-foot"><div><strong>Begin gerust klein.</strong><span>Je kunt later uitbreiden zodra je meer vacatures of acties wilt publiceren.</span></div><a :href="pito.links.business" target="_blank" rel="noopener">Bekijk alle zakelijke informatie <ArrowRight :size="17" /></a></div></div></section>
  <section class="business-v2-organisations"><div class="shell business-v2-organisations-inner"><div><p class="eyebrow">Verenigingen, stichtingen en maatschappelijke organisaties</p><h2>Lokale impact hoort ook zichtbaar te zijn.</h2><p>Neem contact op voor een passende route voor activiteiten, vrijwilligerswerk en maatschappelijke initiatieven.</p></div><div class="business-v2-organisations-links"><RouterLink to="/contact">Ik vertegenwoordig een vereniging <ArrowRight :size="18" /></RouterLink><RouterLink to="/contact">Ik werk voor een stichting <ArrowRight :size="18" /></RouterLink><RouterLink to="/contact">Ik plaats vrijwilligerswerk <ArrowRight :size="18" /></RouterLink></div></div></section>
  <section class="business-v2-purpose"><div class="shell business-v2-purpose-inner"><div><p class="eyebrow eyebrow--light">Samen sterker lokaal</p><h2>Zichtbaarheid die verder gaat dan bereik.</h2></div><div><p>Wanneer lokale bedrijven groeien, groeit de buurt mee. Er ontstaat werk, ontmoeting en een omgeving waar inwoners graag blijven ontdekken.</p><strong>Relevant voor inwoners. Waardevol voor bedrijven. Goed voor de buurt.</strong></div></div></section>
</template>
