<script setup>
import { ArrowRight, Check } from '../icons';
import { pito } from '../stores/content';
</script>

<template>
  <section class="collectives-overview-hero"><div class="shell collectives-overview-hero-inner"><div class="collectives-overview-copy"><p class="eyebrow">PITO Collectieven</p><h1>Verduurzamen met zekerheid.</h1><p>Via PITO kom je in contact met zorgvuldig geselecteerde partners voor persoonlijk advies, betrouwbare installatie en duidelijke afspraken.</p><div class="hero-actions"><a class="button button--orange" href="#collectieven">Kies jouw collectief <ArrowRight :size="18" /></a></div><div class="collectives-overview-proof"><span>Samen geselecteerd</span><strong>Persoonlijk geregeld</strong><span>Powered by PITO</span></div></div><div class="collectives-overview-visual"><img src="/assets/pito-website-v18/collectief-buurtbijeenkomst.png" alt="Buurtbewoners bespreken verduurzaming" /><div><span>PERSOONLIJK ADVIES</span><strong>Eén geselecteerde partner. Jij beslist.</strong></div></div></div></section>
  <section id="collectieven" class="section"><div class="shell"><header class="section-heading"><div><p class="eyebrow">Waar wil je meer over weten?</p><h2>Eerst begrijpen. Dan pas beslissen.</h2></div><p>Een aanvraag is gratis en vrijblijvend. De geselecteerde partner bespreekt jouw situatie persoonlijk.</p></header><div class="card-grid collective-grid">
    <article v-for="item in pito.collectives" :key="item.slug" class="card collective-card" :class="`collective-card--${item.slug}`"><div class="collective-card-main"><div class="collective-card-media"><img :src="item.image" :alt="item.title" /><span class="status-label">{{ item.status }}</span></div><div class="collective-card-copy"><span class="collective-card-kicker">{{ item.short_title.toUpperCase() }}</span><h3>{{ item.title }}</h3><p>{{ item.intro }}</p></div></div><div class="collective-card-actions"><RouterLink :to="`/collectieven/${item.slug}`">Lees hoe het werkt</RouterLink><RouterLink class="collective-card-direct" :to="`/collectieven/${item.slug}#advies`">{{ item.cta_label }} <ArrowRight :size="17" /></RouterLink></div></article>
  </div></div></section>
  <section class="collective-service-band"><div class="shell"><div class="service-grid"><div><span>01</span><h3>Geef je interesse door</h3><p>Laat je basisgegevens achter.</p></div><div><span>02</span><h3>Persoonlijke intake</h3><p>De partner bespreekt je situatie.</p></div><div><span>03</span><h3>Advies op maat</h3><p>Je krijgt een duidelijke vervolgstap.</p></div><div><span>04</span><h3>Jij beslist</h3><p>Vrijblijvend betekent echt vrijblijvend.</p></div></div></div></section>
  <section class="section collective-benefits"><div class="shell"><header class="section-heading"><div><p class="eyebrow">Waarom samen?</p><h2>Meer overzicht. Minder zoekwerk.</h2></div></header><div class="collective-benefit-grid"><article><span>01</span><h3>Efficiënt in de buurt</h3><p>Een partner kan afspraken slimmer plannen wanneer meerdere woningen dichtbij elkaar liggen.</p></article><article><span>02</span><h3>Kosten beperken</h3><p>Efficiëntere planning en gedeelde acquisitie kunnen voordeel opleveren in het voorstel.</p></article><article><span>03</span><h3>Zekerheid</h3><p>We selecteren op advieskwaliteit, uitvoering, service en duidelijke verantwoordelijkheid.</p></article></div></div></section>
</template>
