<script setup>
import { reactive, ref } from 'vue';
import axios from 'axios';
import { Check } from '../icons';
const sent = ref(false); const sending = ref(false); const errors = ref({});
const form = reactive({ name: '', email: '', phone: '', organisation: '', subject: 'Vraag over aanbod', message: '', consent: false });
async function submit() { sending.value = true; errors.value = {}; try { await axios.post('/api/contact', form); sent.value = true; } catch (error) { errors.value = error.response?.data?.errors || { form: ['Versturen lukt nu niet.'] }; } finally { sending.value = false; } }
</script>

<template>
  <section class="form-page"><div class="shell form-page-grid"><div><p class="eyebrow">Contact</p><h1>Waar kunnen we je mee helpen?</h1><p class="lead">Een vraag over aanbod, een collectief of samenwerking? Stuur ons een bericht. We zorgen dat het bij de juiste persoon terechtkomt.</p><div class="expectation"><h3>Handig om te vermelden</h3><p>Noem het aanbod of collectief, je gemeente en wat je precies wilt weten. Deel geen gevoelige informatie.</p></div></div><div v-if="sent" class="success-panel"><Check :size="34" /><h3>Bericht ontvangen.</h3><p>We nemen zo snel mogelijk contact met je op.</p></div><form v-else class="lead-form" @submit.prevent="submit"><label class="field"><span>Naam</span><input v-model="form.name" required autocomplete="name" /></label><label class="field"><span>E-mailadres</span><input v-model="form.email" required type="email" autocomplete="email" /></label><label class="field"><span>Telefoonnummer <small>optioneel</small></span><input v-model="form.phone" type="tel" autocomplete="tel" /></label><label class="field"><span>Organisatie <small>optioneel</small></span><input v-model="form.organisation" /></label><label class="field"><span>Onderwerp</span><select v-model="form.subject"><option>Vraag over aanbod</option><option>Vraag over een collectief</option><option>Samenwerken met PITO</option><option>Privacyvraag of verzoek</option><option>Anders</option></select></label><label class="field"><span>Bericht</span><textarea v-model="form.message" required rows="6" /></label><label class="collective-consent"><input v-model="form.consent" type="checkbox" required /> Ik ga akkoord met de verwerking van mijn gegevens volgens de <RouterLink to="/privacy">privacyverklaring</RouterLink>.</label><p v-if="errors.form" class="form-error">{{ errors.form[0] }}</p><button class="button button--orange" :disabled="sending" type="submit">{{ sending ? 'Even versturen…' : 'Verstuur bericht' }}</button></form></div></section>
</template>
